# Generated by Django 3.0.7 on 2020-10-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201012_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_view',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
