# Generated by Django 3.0.7 on 2020-10-15 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201015_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment_post',
        ),
    ]
