# Generated by Django 3.0.7 on 2020-10-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20201016_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_post',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
