# Generated by Django 3.0.7 on 2020-10-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20201016_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
