# Generated by Django 3.0.7 on 2020-10-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20201021_1616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
